//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RickyShop_Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Descontos
    {
        public int ID_Cupao { get; set; }
        public int ID_Utilizador { get; set; }
        public int Desconto { get; set; }
        public int EstadoCupao { get; set; }
    
        public virtual Utilizadores Utilizadores { get; set; }
    }
}
