//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RickyShop_Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadoUtilizadores
    {
        public int ID_Utilizadores { get; set; }
        public System.DateTime LogOn { get; set; }
        public System.DateTime LogOff { get; set; }
    
        public virtual Utilizadores Utilizadores { get; set; }
    }
}
