//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RickyShop_Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedidos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pedidos()
        {
            this.PedidosDetalhes = new HashSet<PedidosDetalhes>();
        }
    
        public int ID_Pedido { get; set; }
        public int ID_Utilizador { get; set; }
        public System.DateTime DataDoPedido { get; set; }
        public System.DateTime DataDeEntrega { get; set; }
        public string LocalDeEntrega { get; set; }
        public string CodigoPostal { get; set; }
        public decimal PreçoTotal { get; set; }
        public int ID_Estado { get; set; }
        public double Desconto { get; set; }
    
        public virtual EstadoDoPedido EstadoDoPedido { get; set; }
        public virtual Utilizadores Utilizadores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidosDetalhes> PedidosDetalhes { get; set; }
    }
}
