//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RickyShop_Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produto()
        {
            this.Carrinho = new HashSet<Carrinho>();
            this.PedidosDetalhes = new HashSet<PedidosDetalhes>();
            this.ProdutosFavoritos = new HashSet<ProdutosFavoritos>();
        }
    
        public int ID_Produto { get; set; }
        public decimal PreçoPorQuantidade { get; set; }
        public int ID_Categoria { get; set; }
        public int ID_Fornecedor { get; set; }
        public int QuantidadeStock { get; set; }
        public string ImagemPath { get; set; }
        public string Descrição { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Carrinho> Carrinho { get; set; }
        public virtual Categoria Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidosDetalhes> PedidosDetalhes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdutosFavoritos> ProdutosFavoritos { get; set; }
    }
}
