//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RickyShop_Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promo
    {
        public int ID_Promo { get; set; }
        public string Nome { get; set; }
        public string Descrição { get; set; }
        public string Path_Logo { get; set; }
        public System.DateTime InicioData_Promo { get; set; }
        public System.DateTime FimData_Promo { get; set; }
        public int Desconto { get; set; }
        public Nullable<int> ID_Categoria { get; set; }
        public Nullable<int> ID_Marca { get; set; }
    }
}
