//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RickyShop_Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Promo()
        {
            this.PromoDetalhes = new HashSet<PromoDetalhes>();
        }
    
        public int ID_Promo { get; set; }
        public System.DateTime InicioData_Promo { get; set; }
        public System.DateTime FimData_Promo { get; set; }
        public string Path_Logo { get; set; }
        public string Descrição { get; set; }
        public int Desconto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PromoDetalhes> PromoDetalhes { get; set; }
    }
}
