//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RickyShop_Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reporte
    {
        public int ID_Reporte { get; set; }
        public string Nome_Utilizador { get; set; }
        public string Email { get; set; }
        public string Titulo_Reporte { get; set; }
        public string Descrição { get; set; }
    }
}
