//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAP_RickyShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logs
    {
        public int ID_Log { get; set; }
        public int ID_Utilizador { get; set; }
        public Nullable<System.DateTime> Erro_Login { get; set; }
        public Nullable<System.DateTime> Login { get; set; }
        public Nullable<System.DateTime> LogOff { get; set; }
        public string IP_TentativaLogin { get; set; }
    
        public virtual Utilizadores Utilizadores { get; set; }
    }
}
