//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAP_RickyShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdutosFavoritos
    {
        public int ID_Favoritos { get; set; }
        public int ID_Produto { get; set; }
        public int ID_Utilizador { get; set; }
    
        public virtual Produto Produto { get; set; }
        public virtual Utilizadores Utilizadores { get; set; }
    }
}
